{% set name = "edlib" %}
{% set version = "1.3.9.post1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/edlib-{{ version }}.tar.gz
  sha256: b0fb6e85882cab02208ccd6daa46f80cb9ff1d05764e91bf22920a01d7a6fbfa

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - cmake
  host:
    - cython
    - pip
    - python
  run:
    - python

test:
  imports:
    - edlib
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Martinsos/edlib
  summary: Lightweight, super fast library for sequence alignment using edit (Levenshtein) distance.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - raybellwaves
